name: PhiChat CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  issues: write
  security-events: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run:
          pip install -r requirements.txt

      - name: Run static type check
        run: |
          pip install mypy
          mypy app

  tests:
    runs-on: ubuntu-latest

    env:
      APP_NAME: "PhiChat"
      APP_ENV: "test"
      DATABASE_URL: "sqlite+aiosqlite:///file::memory:?cache=shared"
      SECRET_KEY: ""
      ACCESS_TOKEN_EXPIRE_MINUTES: 3600

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run:
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

  docker-image-scan:
    name: Docker Image Scan
    runs-on: ubuntu-latest
    needs: [build, tests]
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image for scan
        run: docker build -t phichat-backend-scan -f Dockerfile .

      - name: Docker Scout Scan
        uses: docker/scout-action@v1.18.1
        with:
          dockerhub-user: ${{ secrets.DOCKER_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
          command: quickview,cves
          sarif-file: docker-scout-report.sarif

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker-scout-findings
          path: docker-scout-report.sarif

  version:
    runs-on: ubuntu-latest
    needs: [docker-image-scan]
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Bump version
        id: Bump
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PHICHAT_PAT }}
          DEFAULT_BUMP: patch

      - name: Output new version
        run: echo "New version - ${{ steps.bump.outputs.new_tag }}"

  docker-publish:
    runs-on: ubuntu-latest
    needs: [version]
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/phichat-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/phichat-backend:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/phichat-backend:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: [docker-publish]
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Flyctl install
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io using Dockerhub image
        run: flyctl deploy --remote-only --image ${{ secrets.DOCKER_USERNAME }}/phichat-backend:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
